language: nodejs
before_script:
- npm install
- npm run build
deploy:
  provider: bluemixcloudfoundry
  username: apikey
  password:
    secure: I2xw0urCbqsg6pnvht/kf8hcDtb9BdX6YTrjl+f0pai1jc20zJf9p1vLSp9u+ZDbl2UcnJN6UQS2TTxgeUmtRAN+KRJP3JASYJR3HSU3KQqIyqQerPuCJXrLsPt0L2327oZUwZZS40m5oAKo2A3xATLsc7D8m5nx3gyY6lGt34ymcXPV9A9qssRjNjoOTOtBuVEGtPZP6DKO/1DM/KFxldwtc7zJ5uZsmZ39IB4uSGkeFjTKVgOEjFfhwLHfe33QECf/pKX/irxtUB7xafbgnat6GhvJGwsEV8IOKg9S+kPPBdqVY5Ed6evvkhnAdJ6YjwX5+nm0wTbxcqws4hub0S6/KIozZTygfIcFN0mAfpbcDh3YHL64bhaCVFK44HHgksC5HHIVKaXduB9B7Fd6AqNt00ArhCSKVwXX3FKhJRrnNaAQu0BqlvF7Fzxfsz8ftHDW/uOIeVxCohL8zHZ29kZRBsnP3WRY2ugA68wXGjuNnh5AcWQz1e2WRULkg/N3b2gPAT7HqsLOAtMb3lud6eP+VYKBd7g4DxLCVsAwKNKDbyYLjyFwjS/iHad/4Ak15cbhmJjTD/QfYvOccZ5hAvJ8v6R7931Z+2sPNgmqn80g2i4Hb/iEEu2FFFjxneFiG2lCi9+NR9Qi8/WvdXUe9J3LgdjhxjHhtySQFEwc5O4=
  organization: thore@datensumpf.de
  space: thore.kruess
  on:
    branch: master
